# Generated by Django 3.2.4 on 2022-02-07 05:53

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpawRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('ogc_fid', models.IntegerField(blank=True, null=True)),
                ('office', models.CharField(blank=True, max_length=64, null=True)),
                ('hectares', models.FloatField(blank=True, null=True)),
                ('md5_rowhash', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4283)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Layer GeoJSON')),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_features', to='sqs.layer')),
            ],
        ),
        migrations.CreateModel(
            name='LayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Layer GeoJSON')),
                ('version', models.IntegerField(editable=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sqs.layer')),
            ],
            options={
                'unique_together': {('version', 'layer')},
            },
        ),
    ]
