# Generated by Django 3.2.4 on 2022-05-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sqs.layer'),
        ),
    ]
