# Generated by Django 3.2.4 on 2022-05-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0002_alter_feature_layer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DpawRegion',
        ),
    ]
