# Generated by Django 3.2.4 on 2022-05-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0003_delete_dpawregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='layerhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
