# Generated by Django 3.2.4 on 2022-05-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0004_auto_20220517_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='name',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='layerhistory',
            old_name='name',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='layerhistory',
            name='type',
        ),
    ]
